#!/usr/bin/env bash

##############################################################################
##
##  git clone start up script for UN*X
##
##############################################################################
## rm -rf gitlibs
git clone https://github.com/ShinChven/CommonLib.git gitlibs/commonlib